import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Link from 'next/link';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Auth Example</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Auth Example</h1>

        <div className={styles.grid}>
          <Link href='/register' className={styles.card}>
            <h2>Register &rarr;</h2>
            <p>Resgistration Example</p>
          </Link>

          <Link href='/login' className={styles.card}>
            <h2>Login &rarr;</h2>
            <p>Login Example</p>
          </Link>

          <Link href='/user' className={styles.card}>
            <h2>User Data &rarr;</h2>
            <p>Example to use user data within the app</p>
          </Link>

          <Link href='/todoapp' className={styles.card}>
            <h2>TodoApp &rarr;</h2>
            <p>Using redux toolkit</p>
          </Link>
        </div>
      </main>
    </div>
  );
}
